//
// Created by Антон on 07.07.2021.
//

#ifndef TIMES_AND_PLANES_OPTIMIZATION_2021_07_ERRORS_H
#define TIMES_AND_PLANES_OPTIMIZATION_2021_07_ERRORS_H
enum Error
{
    FILE_NOT_EXIST = -1,
    FILE_NOT_ALLOWED_FORMAT = -2,
    DUPLICATE_NAME = -3,
    NO_OBJECT = -4
};
#endif //TIMES_AND_PLANES_OPTIMIZATION_2021_07_ERRORS_H
